import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useEffect, useState } from 'react';
import { ethers } from 'ethers';
import { useAccount, useProvider, useSigner } from 'wagmi';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import propertySaleAbi from '../abi/sale'; // Ensure this path is correct

const Home: NextPage = () => {
  const { address, isConnected } = useAccount();
  const provider = useProvider();
  const { data: signer } = useSigner();

  const [contract, setContract] = useState<ethers.Contract | null>(null);
  const [houses, setHouses] = useState([
    { id: 1, name: 'Cozy Cottage', price: '$200,000', image: 'https://images.unsplash.com/photo-1618660920685-4505debb785a?q=80&w=3871&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { id: 2, name: 'Modern Villa', price: '$500,000', image: 'https://images.unsplash.com/photo-1592676720632-e0f4741e1f46?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YnJpdGlzaCUyMGhvdXNlfGVufDB8fDB8fHww' },
    { id: 3, name: 'Beach House', price: '$750,000', image: 'https://plus.unsplash.com/premium_photo-1694475477920-8064c7783ed9?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YnJpdGlzaCUyMGhvdXNlfGVufDB8fDB8fHww' },
    { id: 4, name: 'Mountain Retreat', price: '$300,000', image: 'https://images.unsplash.com/photo-1564866657319-d3763c69e0f6?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YnJpdGlzaCUyMGhvdXNlfGVufDB8fDB8fHww' },
  ]);

  useEffect(() => {
    if (isConnected && signer) {
      const contractAddress = 'your_contract_address_here'; // Replace with your deployed contract address
      const contractInstance = new ethers.Contract(contractAddress, propertySaleAbi, signer);
      setContract(contractInstance);
    }
  }, [isConnected, signer]);

  const initiateOffer = async (houseId: number) => {
    if (contract) {
      try {
        const price = ethers.utils.parseUnits('200000', 'ether'); // Replace with actual price
        const tx = await contract.initiateOffer(price);
        await tx.wait();
        alert('Offer initiated!');
      } catch (error) {
        console.error(error);
      }
    }
  };

  return (
      <div className="min-h-screen flex flex-col">
        <Head>
          <title>XRPLendNet</title>
          <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <main className="flex-grow">
          <div className="py-10 bg-blue-300 pl-auto pr-10">
            <div className="flex justify-start">
              <div className="ml-12">
                <ConnectButton />
              </div>
            </div>
          </div>

          <div className="flex justify-center items-center mt-20 mb-10">
            <div className="text-4xl text-center">
              <p className="text-blue-900">House Marketplace</p>
            </div>
          </div>
          <div className="flex justify-center items-center mt-10 mb-10">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
              {houses.map(house => (
                  <div key={house.id} className="border rounded-lg p-4 text-center">
                    <img src={house.image} alt={house.name} className="w-full h-48 object-cover rounded-md mb-4" />
                    <h2 className="text-2xl mb-2">{house.name}</h2>
                    <p className="text-xl mb-4">{house.price}</p>
                    <Link href={`/house/${house.id}`} className="text-blue-500">View Details</Link>
                    <button
                        className="mt-4 bg-blue-500 text-white py-2 px-4 rounded"
                        onClick={() => initiateOffer(house.id)}
                    >
                      Initiate Offer
                    </button>
                  </div>
              ))}
            </div>
          </div>
        </main>

        <footer>
          <div className="py-5 bg-blue-300">
            <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank" className="text-blue-900 flex justify-center">
              Made with ❤️ by your friends at #60DaysofXRPL London 😎
            </a>
          </div>
        </footer>
      </div>
  );
};

export default Home;
