// pages/index.tsx

import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  const houses = [
    { id: 1, name: 'Cozy Cottage', price: '£200,000', image: 'https://images.unsplash.com/photo-1618660920685-4505debb785a?q=80&w=3871&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' },
    { id: 2, name: 'Modern Villa', price: '£500,000', image: 'https://images.unsplash.com/photo-1592676720632-e0f4741e1f46?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YnJpdGlzaCUyMGhvdXNlfGVufDB8fDB8fHww' },
    { id: 3, name: 'Beach House', price: '£750,000', image: 'https://plus.unsplash.com/premium_photo-1694475477920-8064c7783ed9?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YnJpdGlzaCUyMGhvdXNlfGVufDB8fDB8fHww' },
    { id: 3, name: 'Beach House', price: '£750,000', image: 'https://plus.unsplash.com/premium_photo-1694475477920-8064c7783ed9?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YnJpdGlzaCUyMGhvdXNlfGVufDB8fDB8fHww' },
  ];

  return (
      <div className="min-h-screen flex flex-col">
        <Head>
          <title>Proply</title>
          <meta
              content="Generated by @rainbow-me/create-rainbowkit"
              name="description"
          />
          <link href="/favicon.ico" rel="icon"/>
        </Head>

        <main className="flex-grow">
          <div className="py-10 bg-[#232329] pl-auto pr-10">
            <div className="flex justify-start">
              <div className="ml-12 flex">

                <ConnectButton />
                <h1 className="text-4xl text-white text-center">Proply</h1>
              </div>
            </div>
          </div>



          {/* House Marketplace Section */}
          <div className="flex justify-center items-center mt-20 mb-10">
            <div className="text-4xl text-center">
              <p className="text-blue-900">House Marketplace</p>
            </div>
          </div>
          <div className="flex justify-center items-center mt-10 mb-10">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
              {houses.map(house => (
                  <div key={house.id} className="border rounded-lg p-4 text-center">
                    <img src={house.image} alt={house.name} className="w-full h-48 object-cover rounded-md mb-4"/>
                    <h2 className="text-2xl mb-2">{house.name}</h2>
                    <p className="text-xl mb-4">{house.price}</p>
                    <Link href={`/house/${house.id}`} className="text-blue-500">View Details</Link>
                  </div>
              ))}
            </div>
          </div>
        </main>

        <footer>
          <div className="py-5 bg-[#232329]">
            <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank"
               className="text-white flex justify-center">
              Made with ❤️ by ProplyTeam
            </a>
          </div>
        </footer>
      </div>
  );
};

export default Home;
